#[path = "build/fat_image.rs"]
mod fat_image;

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Total size of the (decompressed) embedded image. Must match `IMAGE_SIZE` in
/// `src/main.rs` (`IMAGE_BLOCKS_NUM * IMAGE_BLOCK_SIZE`); the generated module
/// re-exports it as `IMAGE_LEN` and `main.rs` asserts the two agree.
const IMAGE_SIZE: usize = 512 * 512;

/// Decompressed size of one ZX0 chunk. Each chunk is compressed independently so
/// the firmware can decode one at a time into a single reusable buffer.
///
/// Capped at 32 KiB on purpose: ZX0's maximum back-reference distance is 32640,
/// so a 32768-byte buffer can serve as *both* the decode window and the resident
/// chunk cache (see `zx0_decompress::decompress_into`). Going larger would force a
/// second output buffer. Must stay `>= zx0_decompress::MIN_WINDOW_LEN` (32641).
const CHUNK_SIZE: usize = 32 * 1024;

fn main() {
    download_svd();
    build_image();
}

/// Build the FAT image from `assets/`, split it into [`CHUNK_SIZE`] chunks,
/// ZX0-compress each independently, and emit:
///   * `$OUT_DIR/image.zx0`  -- the concatenated compressed chunks, and
///   * `$OUT_DIR/image.rs`   -- constants + a `(offset, len)` table into the blob,
/// which `main.rs` pulls in with `include!`.
fn build_image() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets = manifest_dir.join("assets");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let image = fat_image::build(&assets, IMAGE_SIZE, &manifest_dir);

    // Compress each chunk independently; record where it lands in the blob.
    let mut blob = Vec::new();
    let mut table = Vec::new(); // (offset, compressed_len) per chunk
    for chunk in image.chunks(CHUNK_SIZE) {
        let compressed = zx0::compress(chunk);
        table.push((blob.len() as u32, compressed.len() as u32));
        blob.extend_from_slice(&compressed);
    }

    verify_roundtrip(&image, &blob, &table);

    fs::write(out_dir.join("image.zx0"), &blob).expect("Failed to write image.zx0");
    fs::write(out_dir.join("image.rs"), generate_module(&table))
        .expect("Failed to write image.rs");

    let ratio = 100.0 * blob.len() as f64 / image.len() as f64;
    println!(
        "cargo:warning=Embedded image: {} chunks, {} -> {} bytes ZX0 ({:.1}%)",
        table.len(),
        image.len(),
        blob.len(),
        ratio
    );

    // Rebuild the image whenever the asset tree or the builder itself changes.
    // (Cargo already re-runs this script when build.rs changes.)
    println!("cargo:rerun-if-changed=build/fat_image.rs");
    rerun_if_changed_recursive(&assets);
    // Entry timestamps come from git history, so a new commit can change the
    // image even when no asset file does; watch the reflog to catch commits.
    let git_log = manifest_dir.join(".git/logs/HEAD");
    if git_log.exists() {
        println!("cargo:rerun-if-changed={}", git_log.display());
    }
}

/// Decode the compressed blob with the firmware's own decompressor and assert it
/// reproduces `image` exactly, using the same single-buffer scheme the device
/// does. Catches any ZX0 compressor/decompressor mismatch before it is flashed.
fn verify_roundtrip(image: &[u8], blob: &[u8], table: &[(u32, u32)]) {
    let mut buf = vec![0u8; CHUNK_SIZE];
    let mut reconstructed = Vec::with_capacity(image.len());
    for &(offset, len) in table {
        let compressed = &blob[offset as usize..(offset + len) as usize];
        let decoded = zx0_decompress::decompress_into(compressed, &mut buf)
            .expect("embedded chunk must decode back");
        reconstructed.extend_from_slice(decoded);
    }
    assert!(
        reconstructed == image,
        "ZX0 round-trip mismatch: decompressed blob does not match the source image"
    );
}

/// Render the generated `image.rs` source pulled in by `main.rs`.
fn generate_module(table: &[(u32, u32)]) -> String {
    let mut entries = String::new();
    for (offset, len) in table {
        entries.push_str(&format!("    ({offset}, {len}),\n"));
    }
    format!(
        "// @generated by build.rs -- do not edit.\n\
         /// Decompressed length of the whole image.\n\
         pub const IMAGE_LEN: usize = {image_len};\n\
         /// Decompressed length of one chunk (also the decode buffer size).\n\
         pub const CHUNK_SIZE: usize = {chunk_size};\n\
         /// Number of ZX0 chunks the image is split into.\n\
         pub const CHUNK_COUNT: usize = {count};\n\
         /// `(offset, compressed_len)` of each chunk within [`COMPRESSED`].\n\
         pub static CHUNK_TABLE: [(u32, u32); CHUNK_COUNT] = [\n{entries}];\n\
         /// The concatenated, independently ZX0-compressed chunks.\n\
         pub static COMPRESSED: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/image.zx0\"));\n",
        image_len = IMAGE_SIZE,
        chunk_size = CHUNK_SIZE,
        count = table.len(),
    )
}

/// Emit `rerun-if-changed` for `path` and, if it is a directory, everything
/// underneath it, so adding/removing/editing any asset triggers a rebuild.
fn rerun_if_changed_recursive(path: &Path) {
    println!("cargo:rerun-if-changed={}", path.display());
    if path.is_dir() {
        for entry in fs::read_dir(path).into_iter().flatten().flatten() {
            rerun_if_changed_recursive(&entry.path());
        }
    }
}

/// Download the patched SVD for the target chip into the project root (once).
fn download_svd() {
    // Retrieve the target chip series from the environment variable
    let target = "stm32f401.svd";

    let file_name = format!("{target}.svd");
    let output_path = Path::new(&file_name);
    let url = format!("https://stm32-rs.github.io/stm32-rs/{target}.patched");

    // Check if the file already exists
    if output_path.exists() {
        println!(
            "SVD file already exists at {:?}, skipping download.",
            output_path
        );
    } else {
        // Ensure the output directory exists
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent).expect("Failed to create directory for SVD file");
        }

        // Download the file
        println!("Downloading SVD file from {}...", url);
        let response = reqwest::blocking::get(&url).expect("Failed to fetch SVD file");
        let content = response.text().expect("Failed to read response body");

        // Write the downloaded content to the file
        let mut file = fs::File::create(output_path).expect("Failed to create SVD file");
        file.write_all(content.as_bytes())
            .expect("Failed to write SVD file");

        println!("SVD file saved to {:?}", output_path);
    }
}
