[package]
name = "simple_mass_storage"
version = "0.1.0"
authors = ["Schuwi <schuwi4@gmail.com>"]
edition = "2021"

[dependencies]
# "critical-section-single-core" needed for static_cell crate
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-probe = { version = "0.3.1", features = ["defmt"] }
rtic = { version = "2", features = ["thumbv7-backend"] }
defmt-rtt = "1.2.0"
defmt = "1.1.0"
static_cell = "2.1.1"
usb-device = "0.3.2"
usbd-storage = { version = "2.0.0", features = ["bbb", "defmt", "scsi"] }
stm32-device-signature = { version = "0.3.3", features = ["stm32f4"] }

[dependencies.stm32f4xx-hal]
version = "0.23.0"
features = ["stm32f401", "rtic2", "defmt", "usb_fs"]


[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }


# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"
